### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Mr Volta 🎵
# description: This will be meta HTML tag content. This can be ignored.
description: Mr Volta, Musician & Producer from Antwerp, Belgium
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Mr Volta
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Musician &amp; Producer
# email: Your E-Mail address for the email button.
email: sandermarccools@gmail.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
facebook_username: mistervolta
facebook-messenger_username: messages/t/240451306669247
youtube_username: UCIcnqfpNXdGgtfMe8p6exTQ
spotify_username: 62gPnJGzBj5srDegUHTzR3
apple_username: mr-volta/306594481
napster_username: mr-volta
soundcloud_username: mistervolta
amazon_username: s?k=Mr+Volta+911874+Records+DK&i=digital-music

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: About
# about_me_description: This will be displayed under the title.
about_me_description: >
  Hi, I'm Mr Volta, a Belgian-based musician and producer.<br><br>

  I was born in Antwerp in 1991 and started playing saxophone when I was 6 years old. Later I thaught myself computer software to make music and fell in love. At the age of 17 I released my first EP under USA Import Music.<br><br>

  After this experience I studied Visual Arts & Installations at 'KASK & Conservatorium / School of Arts Gent' and wasn't really making much music since my focus shifted to <a class="highlight-link" href="/assets/img/mr-volta_visuals.jpg" target="_blank" rel="noreferrer">making visuals</a>.<br><br>

  But the love for sound never disappeared and after finishing my Bachelor I felt the urge to get back to my adventure of making electronic music, trying out different stuff like picking up a jazz flute.<br><br>

  I cover everything from Hip-hop & Rap to Jazz & Blues, to Dance & EDM, to Dubstep, Dubtechno, Triphop, House, Techno,...<br><br>

  Catch me on the net:<br>

  <ul>
  <li><a class="highlight-link" href="https://www.facebook.com/mistervolta/" target="_blank" rel="noreferrer">Facebook</a></li>
  <li><a class="highlight-link" href="https://www.facebook.com/pg/mistervolta/videos/" target="_blank" rel="noreferrer">Facebook Videos</a></li>
  <li><a class="highlight-link" href="https://www.youtube.com/channel/UCIcnqfpNXdGgtfMe8p6exTQ" target="_blank" rel="noreferrer">YouTube</a></li>
  <li><a class="highlight-link" href="https://music.youtube.com/channel/UCm4Y5yx83S6r5dabqipZkrg" target="_blank" rel="noreferrer">YouTube Music</a></li>
  <li><a class="highlight-link" href="https://www.youtube.com/playlist?list=PLaLN0EvcxkHJGLrTlkZOSLsYoSwUWqDYb" target="_blank" rel="noreferrer">YouTube – Top Tracks 🔥</a></li>
  <li><a class="highlight-link" href="https://open.spotify.com/artist/62gPnJGzBj5srDegUHTzR3" target="_blank" rel="noreferrer">Spotify</a></li>
  <li><a class="highlight-link" href="https://soundcloud.com/mistervolta" target="_blank" rel="noreferrer">SoundCloud</a></li>
  <li><a class="highlight-link" href="https://music.apple.com/artist/mr-volta/306594481" target="_blank" rel="noreferrer">Apple&nbsp;Music</a></li>
  <li><a class="highlight-link" href="https://www.amazon.com/s?k=Mr+Volta+911874+Records+DK&i=digital-music" target="_blank" rel="noreferrer">Amazon Music</a></li>
  <li><a class="highlight-link" href="https://napster.com/artist/mr-volta" target="_blank" rel="noreferrer">Napster</a></li>
  <li><a class="highlight-link" href="https://www.deezer.com/en/artist/50753152" target="_blank" rel="noreferrer">Deezer</a></li>
  <li><a class="highlight-link" href="https://tidal.com/browse/artist/10283550" target="_blank" rel="noreferrer">Tidal</a></li>
  <li><a class="highlight-link" href="https://www.kkbox.com/sg/en/artist/TIYtr6niluwruZ0F0ixmp08K-index-1.html" target="_blank" rel="noreferrer">KKBOX</a></li>
  <li><a class="highlight-link" href="https://mrvolta.bandcamp.com/" target="_blank" rel="noreferrer">Bandcamp (few older tracks)</a></li>
  </ul>

# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: https://example.com/

# ALBUMS SECTION
# show_albums_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_albums_card: true
# show_albums:
# > setting this to true, will display your listed albums in _data/albums.yml
# > setting this to false, will omit your listed albums
show_albums: true
# albums_title: The will be displayed as the title of your albums
albums_title: Discography

# COMPILATIONS SECTION
show_compilations: true
compilations_title: Compilations

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: To get in touch, book me or partner up, just mail me or send me a message on Messenger&#58;

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: ""

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
    "vendor",
  ]
